---
- name: "Detect changes in logging {{ logging_component }}"
  ansible.builtin.command: >-
    kubectl --kubeconfig=/etc/kubernetes/admin.conf diff --server-side
    --field-manager=devops-foundation -f {{ foundation_dir }}/logging-{{ logging_component }}.yml
  register: logging_diff
  changed_when: false
  failed_when: logging_diff.rc not in [0, 1]

- name: "Apply changes in logging {{ logging_component }}"
  ansible.builtin.command: >-
    kubectl --kubeconfig=/etc/kubernetes/admin.conf apply --server-side
    --field-manager=devops-foundation -f {{ foundation_dir }}/logging-{{ logging_component }}.yml
  when: logging_diff.rc == 1
  changed_when: true
